# Project-wide options and platform-specific settings

# ============================================================================
# Build Options
# ============================================================================

# Export compile commands for IDE/tools support
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# Build shared libraries by default (for LGPL compliance)
# Users can override with: cmake -DBUILD_SHARED_LIBS=OFF
# Note: On Windows, static libraries are default due to DLL export complexities
if(WIN32)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build shared libraries (.so/.dylib/.dll)")
else()
    set(BUILD_SHARED_LIBS ON CACHE BOOL "Build shared libraries (.so/.dylib/.dll)")
endif()

# Set position independent code for shared libraries
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

# ============================================================================
# Application Build Options
# ============================================================================

option(BUILD_MEDIA_SERVER "Build live555MediaServer executable" ON)
option(BUILD_PROXY_SERVER "Build live555ProxyServer executable" ON)
option(BUILD_HLS_PROXY "Build live555HLSProxy executable" ON)
option(BUILD_TEST_PROGS "Build test programs" OFF)

# ============================================================================
# Platform-Specific Definitions
# ============================================================================

# Platform-specific compile definitions for live555
if(UNIX AND NOT APPLE)
    set(LIVE555_COMPILE_DEFINITIONS
        SOCKLEN_T=socklen_t
        _LARGEFILE_SOURCE=1
        _FILE_OFFSET_BITS=64
    )
elseif(APPLE)
    set(LIVE555_COMPILE_DEFINITIONS
        SOCKLEN_T=socklen_t
        _LARGEFILE_SOURCE=1
        _FILE_OFFSET_BITS=64
        BSD=1
        HAVE_SOCKADDR_LEN=1
    )
elseif(WIN32)
    set(LIVE555_COMPILE_DEFINITIONS
        SOCKLEN_T=int
        NO_SSTREAM=1
        NO_GETIFADDRS=1
        _CRT_SECURE_NO_WARNINGS
        _CRT_NONSTDC_NO_WARNINGS
    )
endif()

# ============================================================================
# Development Tools
# ============================================================================

# Create symbolic link or copy compile_commands.json to project root
# Note: compile_commands.json is only generated by Makefile/Ninja generators,
# not by Visual Studio or other IDE generators.
if(CMAKE_EXPORT_COMPILE_COMMANDS)
    if(CMAKE_GENERATOR MATCHES "Ninja|Makefiles")
        if(WIN32)
            # On Windows, symlinks require admin privileges, so use copy instead
            add_custom_target(compile_commands_copy ALL
                COMMAND ${CMAKE_COMMAND} -E copy_if_different
                    ${CMAKE_BINARY_DIR}/compile_commands.json
                    ${CMAKE_SOURCE_DIR}/compile_commands.json
                COMMENT "Copying compile_commands.json to project root"
                VERBATIM
            )
            message(STATUS "compile_commands.json will be copied to project root after build")
        else()
            # Create symlink after all targets are defined
            add_custom_target(compile_commands_symlink ALL
                COMMAND ${CMAKE_COMMAND} -E create_symlink
                    ${CMAKE_BINARY_DIR}/compile_commands.json
                    ${CMAKE_SOURCE_DIR}/compile_commands.json
                COMMENT "Creating symlink: compile_commands.json -> build/compile_commands.json"
                VERBATIM
            )
            message(STATUS "compile_commands.json will be symlinked to project root after build")
        endif()
    else()
        message(STATUS "compile_commands.json not supported with ${CMAKE_GENERATOR} generator")
    endif()
endif()
